using System.Text;
using DaxaPos.Application.Printing;
using DaxaPos.Application.Receipts;

namespace DaxaPos.UnitTests.Printing;

/// <summary>
/// PLAN-0005 Milestone E. Proves ESC/POS byte generation from an already-rendered
/// <see cref="ReceiptDocument"/> (Milestone D's output) — pure, dependency-free, mirrors
/// <see cref="DaxaPos.UnitTests.Receipts.ReceiptRendererTests"/>'s style. Never recomputes tax,
/// price, or marker resolution: every byte comes from the document it is handed. No physical
/// printer is needed — assertions decode the generated bytes back to ASCII text.
/// </summary>
public class EscPosReceiptFormatterTests
{
    [Fact]
    public void FormatReceipt_AuMixedBasket_GstFreeMarkerSurvivesByteGeneration()
    {
        var order = new ReceiptOrderInput(
            OrderId: Guid.NewGuid(),
            OrderNumber: 42,
            OpenedAtUtc: DateTimeOffset.UtcNow,
            ClosedAtUtc: DateTimeOffset.UtcNow,
            SubtotalAmount: 19.00m,
            TotalTaxAmount: 1.30m,
            GrandTotalAmount: 20.30m,
            Lines:
            [
                new ReceiptLineInput(Guid.NewGuid(), "Flat white", 1, 5.50m, 5.50m, Voided: false,
                    Taxes: [new ReceiptLineTaxInput("GST", 10m, 5.00m, 0.50m, null, null)]),
                new ReceiptLineInput(Guid.NewGuid(), "Chocolate cake slice", 1, 8.80m, 8.80m, Voided: false,
                    Taxes: [new ReceiptLineTaxInput("GST", 10m, 8.00m, 0.80m, null, null)]),
                new ReceiptLineInput(Guid.NewGuid(), "Loaf of bread", 1, 6.00m, 6.00m, Voided: false,
                    Taxes: [new ReceiptLineTaxInput("GST", 0m, 6.00m, 0.00m, "F", "GST-free")]),
            ],
            Payments: [],
            Refunds: []);
        var document = ReceiptRenderer.Render(order, ReceiptLabelSet.Default);

        var bytes = EscPosReceiptFormatter.FormatReceipt(document);
        var text = DecodeAsciiOnly(bytes);

        Assert.Contains("Flat white", text);
        Assert.Contains("Chocolate cake slice", text);
        Assert.Contains("Loaf of bread", text);
        Assert.Contains("F", text);
        Assert.Contains("F = GST-free", text);
        Assert.Contains("20.30", text);
        Assert.Contains("1.30", text);
        Assert.Contains("Total", text);
        Assert.Contains("Includes GST", text);

        // Product names are never replaced with a tax description (ADR-0011) — the taxable items'
        // own names must still appear verbatim, not just the GST-free one.
        Assert.DoesNotContain("GST-free item", text);
    }

    [Fact]
    public void FormatReceipt_PaymentAndRefundLines_PrintFromDocumentData()
    {
        var paymentId = Guid.NewGuid();
        var refundId = Guid.NewGuid();
        var order = new ReceiptOrderInput(
            Guid.NewGuid(), 7, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow,
            10.00m, 0m, 10.00m,
            Lines: [],
            Payments: [new ReceiptPaymentInput(paymentId, "ManualEftpos", 10.00m, DateTimeOffset.UtcNow)],
            Refunds: [new ReceiptRefundInput(refundId, paymentId, 4.00m, "CustomerRequest", DateTimeOffset.UtcNow)]);
        var document = ReceiptRenderer.Render(order, ReceiptLabelSet.Default);

        var text = DecodeAsciiOnly(EscPosReceiptFormatter.FormatReceipt(document));

        Assert.Contains("ManualEftpos", text);
        Assert.Contains("10.00", text);
        Assert.Contains("CustomerRequest", text);
        Assert.Contains("4.00", text);
    }

    [Fact]
    public void FormatReceipt_StartsWithInitCommand_AndEndsWithCutCommand()
    {
        var document = ReceiptRenderer.Render(EmptyOrder(), ReceiptLabelSet.Default);

        var bytes = EscPosReceiptFormatter.FormatReceipt(document);

        Assert.Equal(EscPosReceiptFormatter.InitBytes, bytes.Take(EscPosReceiptFormatter.InitBytes.Count));
        Assert.Equal(EscPosReceiptFormatter.FullCutBytes, bytes.Skip(bytes.Length - EscPosReceiptFormatter.FullCutBytes.Count));
    }

    [Fact]
    public void FormatReceipt_OrderWithCashPayment_IncludesCashDrawerKickBytes()
    {
        var order = new ReceiptOrderInput(
            Guid.NewGuid(), 1, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow,
            10.00m, 0m, 10.00m,
            Lines: [],
            Payments: [new ReceiptPaymentInput(Guid.NewGuid(), "Cash", 10.00m, DateTimeOffset.UtcNow)],
            Refunds: []);
        var document = ReceiptRenderer.Render(order, ReceiptLabelSet.Default);

        var bytes = EscPosReceiptFormatter.FormatReceipt(document);

        Assert.True(ContainsSubsequence(bytes, EscPosReceiptFormatter.CashDrawerKickBytes));
    }

    [Fact]
    public void FormatReceipt_OrderWithNoCashPayment_OmitsCashDrawerKickBytes()
    {
        var order = new ReceiptOrderInput(
            Guid.NewGuid(), 1, DateTimeOffset.UtcNow, DateTimeOffset.UtcNow,
            10.00m, 0m, 10.00m,
            Lines: [],
            Payments: [new ReceiptPaymentInput(Guid.NewGuid(), "ManualEftpos", 10.00m, DateTimeOffset.UtcNow)],
            Refunds: []);
        var document = ReceiptRenderer.Render(order, ReceiptLabelSet.Default);

        var bytes = EscPosReceiptFormatter.FormatReceipt(document);

        Assert.False(ContainsSubsequence(bytes, EscPosReceiptFormatter.CashDrawerKickBytes));
    }

    [Fact]
    public void GenerateCashDrawerKickBytes_ReturnsTheExactExpectedEscPosSequence()
    {
        // ESC p 0 25 250 — the standard ESC/POS "generate pulse to drawer kick-out connector pin 2"
        // command, a fixed byte sequence any reference thermal printer/ESC-POS spec documents.
        Assert.Equal(new byte[] { 0x1B, 0x70, 0x00, 0x19, 0xFA }, EscPosReceiptFormatter.GenerateCashDrawerKickBytes());
    }

    [Fact]
    public void FormatReceipt_IsDeterministic()
    {
        var document = ReceiptRenderer.Render(EmptyOrder(), ReceiptLabelSet.Default);

        var first = EscPosReceiptFormatter.FormatReceipt(document);
        var second = EscPosReceiptFormatter.FormatReceipt(document);

        Assert.Equal(first, second);
    }

    private static ReceiptOrderInput EmptyOrder() => new(
        Guid.NewGuid(), 1, DateTimeOffset.UtcNow, null, 0m, 0m, 0m, Lines: [], Payments: [], Refunds: []);

    /// <summary>Strips non-ASCII-printable control bytes so assertions can search the rendered text.</summary>
    private static string DecodeAsciiOnly(byte[] bytes) =>
        Encoding.ASCII.GetString(bytes.Select(b => b is >= 0x20 and < 0x7F or (byte)'\n' or (byte)'\r' ? b : (byte)' ').ToArray());

    private static bool ContainsSubsequence(IReadOnlyList<byte> haystack, IReadOnlyList<byte> needle)
    {
        for (var i = 0; i <= haystack.Count - needle.Count; i++)
        {
            var matches = true;
            for (var j = 0; j < needle.Count; j++)
            {
                if (haystack[i + j] != needle[j])
                {
                    matches = false;
                    break;
                }
            }

            if (matches)
            {
                return true;
            }
        }

        return false;
    }
}
