// <auto-generated />
using System;
using DaxaPos.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DaxaPos.Persistence.Migrations
{
    [DbContext(typeof(DaxaDbContext))]
    [Migration("20260705034151_AddProductCatalogueFoundation")]
    partial class AddProductCatalogueFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DaxaPos.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AfterValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeValue")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoleSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("SessionTokenHash")
                        .IsUnique();

                    b.HasIndex("StaffMemberId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TerminalId");

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.DeviceCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RotatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TenantId");

                    b.ToTable("device_credentials", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.DeviceRegistrationPin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxUses")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.ToTable("device_registration_pins", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Category = 1,
                            Code = "organisations.manage",
                            Description = "Create/update organisations."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Category = 1,
                            Code = "locations.manage",
                            Description = "Create/update locations within an organisation."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000003"),
                            Category = 1,
                            Code = "terminals.manage",
                            Description = "Create/update terminals within a location."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000004"),
                            Category = 1,
                            Code = "devices.manage",
                            Description = "Rotate/revoke device credentials, list devices."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000005"),
                            Category = 1,
                            Code = "devices.register",
                            Description = "Generate/rotate device registration PINs."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000006"),
                            Category = 1,
                            Code = "staff.manage",
                            Description = "Create staff members, reset PIN, assign roles, disable staff."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000007"),
                            Category = 1,
                            Code = "users.manage",
                            Description = "Create local manager/admin users, assign roles."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000008"),
                            Category = 1,
                            Code = "sessions.manage",
                            Description = "Force-revoke another identity's active session."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000009"),
                            Category = 1,
                            Code = "catalog.manage",
                            Description = "Create/update product categories, products, variants, and modifiers; assign product tax categories (OI-0007)."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000010"),
                            Category = 1,
                            Code = "pricing.manage",
                            Description = "Create/update location price overrides and venue tax configuration."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000011"),
                            Category = 1,
                            Code = "menus.manage",
                            Description = "Create/update menus, sections, and availability rules."
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000012"),
                            Category = 0,
                            Code = "catalog.sold-out-toggle",
                            Description = "Toggle a product's sold-out state at a location."
                        });
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("SupersededByProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SupersededByProductId");

                    b.HasIndex("TaxCategoryId");

                    b.HasIndex("TenantId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.ToTable("product_categories", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Description = "Full access across all tenants and functions.",
                            IsSystemDefined = true,
                            Name = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Description = "Full access within their own organisation.",
                            IsSystemDefined = true,
                            Name = "OrganisationOwner"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Description = "Store-level management within an assigned location.",
                            IsSystemDefined = true,
                            Name = "VenueManager"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Description = "Operational POS use only (staff PIN login).",
                            IsSystemDefined = true,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Description = "Limited, audited support access.",
                            IsSystemDefined = true,
                            Name = "SupportAccess"
                        });
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000001"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000002"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000010")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000011")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000003"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000012")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000005"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("00000000-0000-0000-0001-000000000004"),
                            PermissionId = new Guid("00000000-0000-0000-0002-000000000012")
                        });
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LockedOutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("OrganisationId", "StaffCode")
                        .IsUnique();

                    b.ToTable("staff_members", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.StaffMemberRole", b =>
                {
                    b.Property<Guid>("StaffMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("StaffMemberId", "RoleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("staff_member_roles", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaxTreatment")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("tax_categories", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxCategoryDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaxCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaxDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TaxCategoryId");

                    b.HasIndex("TaxDefinitionId");

                    b.HasIndex("TenantId");

                    b.ToTable("tax_category_definitions", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalculationScope")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IncludedInPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("JurisdictionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("JurisdictionType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("ReceiptMarkerCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReceiptMarkerLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReportingCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoundingMode")
                        .HasColumnType("integer");

                    b.Property<int>("RoundingPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("SourceTemplateCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("tax_definitions", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxDefinitionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalculationScope")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IncludedInPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("JurisdictionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("JurisdictionType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("RatePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("ReceiptMarkerCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReceiptMarkerLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ReportingCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoundingMode")
                        .HasColumnType("integer");

                    b.Property<int>("RoundingPrecision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tax_definition_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            CalculationScope = 0,
                            Code = "AU_GST_10",
                            CountryCode = "AU",
                            IncludedInPrice = true,
                            IsActive = true,
                            JurisdictionName = "Australia",
                            JurisdictionType = 0,
                            Name = "GST",
                            RatePercent = 10m,
                            ReportingCategory = "GST",
                            RoundingMode = 0,
                            RoundingPrecision = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            CalculationScope = 0,
                            Code = "AU_GST_FREE",
                            CountryCode = "AU",
                            IncludedInPrice = true,
                            IsActive = true,
                            JurisdictionName = "Australia",
                            JurisdictionType = 0,
                            Name = "GST",
                            RatePercent = 0m,
                            ReceiptMarkerCode = "F",
                            ReceiptMarkerLabel = "GST-free",
                            ReportingCategory = "GSTFree",
                            RoundingMode = 0,
                            RoundingPrecision = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            CalculationScope = 0,
                            Code = "NZ_GST_15",
                            CountryCode = "NZ",
                            IncludedInPrice = true,
                            IsActive = true,
                            JurisdictionName = "New Zealand",
                            JurisdictionType = 0,
                            Name = "GST",
                            RatePercent = 15m,
                            ReportingCategory = "GST",
                            RoundingMode = 0,
                            RoundingPrecision = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000004"),
                            CalculationScope = 0,
                            Code = "NZ_ZERO_RATED",
                            CountryCode = "NZ",
                            IncludedInPrice = true,
                            IsActive = true,
                            JurisdictionName = "New Zealand",
                            JurisdictionType = 0,
                            Name = "GST",
                            RatePercent = 0m,
                            ReceiptMarkerCode = "Z",
                            ReceiptMarkerLabel = "Zero-rated",
                            ReportingCategory = "ZeroRated",
                            RoundingMode = 0,
                            RoundingPrecision = 2
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000005"),
                            CalculationScope = 0,
                            Code = "NZ_EXEMPT",
                            CountryCode = "NZ",
                            IncludedInPrice = true,
                            IsActive = true,
                            JurisdictionName = "New Zealand",
                            JurisdictionType = 0,
                            Name = "GST",
                            RatePercent = 0m,
                            ReceiptMarkerCode = "E",
                            ReceiptMarkerLabel = "Exempt",
                            ReportingCategory = "Exempt",
                            RoundingMode = 0,
                            RoundingPrecision = 2
                        });
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.ToTable("terminals", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalIdentityProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalSubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockedOutUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Terminal", null)
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.AuthSession", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Terminal", null)
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Device", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.DeviceCredential", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.DeviceRegistrationPin", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Location", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Organisation", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Product", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("SupersededByProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.TaxCategory", null)
                        .WithMany()
                        .HasForeignKey("TaxCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.StaffMember", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.StaffMemberRole", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxCategory", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxCategoryDefinition", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.TaxCategory", null)
                        .WithMany()
                        .HasForeignKey("TaxCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.TaxDefinition", null)
                        .WithMany()
                        .HasForeignKey("TaxDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.TaxDefinition", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.Terminal", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Device", null)
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.User", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DaxaPos.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("DaxaPos.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Organisation", null)
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DaxaPos.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DaxaPos.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
